---
title: 'Geocode addresses with missing lat/lon'
output: html_document
date: '`r Sys.Date()`'
---

```{r init, message=FALSE, warning=FALSE}
library(dplyr)
library(readr)
library(stringr)
library(ggmap)
```

```{r import, message = FALSE}
bus <- read_csv("data/businesses-clean.csv")
```

```{r geocode, message = FALSE, warning = FALSE, eval = FALSE}
miss_latlon <- bus %>%
  filter(is.na(lat) | is.na(lon), !is.na(address), !is.na(zip)) %>%
  select(business_id, address, zip) %>%
  transmute(
    business_id = business_id,
    address     = str_c(address, " SAN FRANCISCO CALIFORNIA ", zip)
  )

miss_latlon <- miss_latlon$address %>% 
  lapply(function(x) {
    Sys.sleep(2)
    geocode(x, source = "dsk")
  }) %>%
  bind_rows %>% 
  bind_cols(miss_latlon)

# save the results
write_csv(miss_latlon, "data/sf-fd-bus-miss-latlon.csv")
```

```{r sneaky, include = FALSE}
miss_latlon <- read_csv("data/sf-fd-bus-miss-latlon.csv")
```

```{r prep and save}
miss_latlon <- right_join(
  bus %>% select(business_id, name, address, zip),
  miss_latlon %>% select(-address),
  by = "business_id"
)

bus <- bus %>% 
  anti_join(miss_latlon, "business_id") %>% 
  bind_rows(miss_latlon)

write_csv(bus, "data/businesses-clean-geo-plus.csv")
```
